name: Coverity Scan

on:
  schedule:
    - cron: '0 0 * * *' # Once every day at 00:00 UTC
env:
  CC: gcc
  ARCH: x86_64
  CONTAINER_NAMESPACE: ghcr.io/opendataplane/odp-docker-images
  OS: ubuntu_20.04
  COVERITY_EMAIL: dummy@opendataplane.org
  COVERITY_PROJECT: ODP

jobs:
  Coverity-analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo docker run -i -v `pwd`:/odp --privileged --shm-size 8g
               -e CC="${CC}" -e GITHUB_SHA="${GITHUB_SHA}"
               -e COVERITY_TOKEN="${{ secrets.COVERITY_TOKEN }}"
               -e COVERITY_EMAIL="${COVERITY_EMAIL}"
               -e COVERITY_PROJECT="${COVERITY_PROJECT}"
               ${CONTAINER_NAMESPACE}/odp-ci-${OS}-${ARCH}-coverity-linux-generic
               /odp/scripts/ci/coverity.sh
